apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdl-sf
  namespace: default
  labels:
    team: teamcrm
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/sbs/pdl-sf/default
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvpdlsf
  env:
    - name: KAFKA_BROKERS
      value: SASL_SSL://b27apvl00045.preprod.local:8443,SASL_SSL://b27apvl00046.preprod.local:8443,SASL_SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_SCREG
      value: https://kafka-test-schema-registry.nais-q.adeo.no
    - name: KAFKA_CLIENTID
      value: pdl-sf
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: aapen-person-pdl-dokument-v1
    - name: SF_OAUTHURL
      value: 'https://test.salesforce.com/services/oauth2/token'
    - name: SF_RESTENDPOINT
      value: '/services/data/v47.0/composite/sobjects'
    - name: MS_BETWEEN_WORK
      value: '600000'

